version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio-s3-server
    ports:
      - "9000:9000"  # API Port
      - "9001:9001"  # Console UI Port
    environment:
      MINIO_ROOT_USER: MINIO_ADMIN # Chave de Acesso (Access Key)
      MINIO_ROOT_PASSWORD: MINIO_PASSWORD # Chave Secreta (Secret Key)
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  minio_data:
